{
 "title": "OTEL Trace Centric",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ServiceName",
    "label": "Service Name",
    "query": {}
   },
   { "name": "ExampleTraceId", "label": "Example TraceId" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"$ServiceName\"} | logfmt | __error__=``"
    }
   ]
  },
  {
   "title": "Service Map",
   "type": "nodeGraph",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "8b200a1e", "operator": "=", "scope": "span" }
     ],
     "limit": 1,
     "metricsQueryType": "range",
     "query": "{}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Http request duration",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "avg by(service_name) (http_server_request_duration_seconds_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "limit": 20, "metricsQueryType": "range", "query": "{}", "tableType": "traces" }
   ]
  },
  {
   "title": "Example Trace",
   "type": "traces",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "limit": 20, "metricsQueryType": "range", "query": "${ExampleTraceId}", "tableType": "traces" }
   ]
  },
  {
   "title": "Span Durations",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    { "limit": 20, "metricsQueryType": "range", "query": "{}", "tableType": "spans" }
   ]
  }
 ]
}